language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
before_install:
  carton
script:
  carton exec prove
notifications:
  irc:
    channels:
      - "irc.freenode.net#okazu"
    on_success: change
    on_failure: always